name: .NET Build

on:
  push:
    branches: [ "feature/cicd" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore Janus.sln

    - name: Build
      run: dotnet build --no-restore Janus.sln

    - name: Publish
      run: dotnet publish ./src/Janus.API/Janus.API.csproj -c Release -o ./release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: janus-api
        path: backend/release/
